// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkmmnhqudzsswxwqrwhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrbW1uaHF1ZHpzc3d4d3Fyd2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mzg1OTMsImV4cCI6MjA2NTMxNDU5M30.YyE8UE41JWDNC_vpayCwNooxrXiF9S9JOLb5KVL8px0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);